### ISSUE TITLE
front-end fetch not hitting backend function

### ISSUE THREAD

**Issue by indefinitelee** [indefinitelee/FPL-Stats#7]
pretty sure it is failing due to the relative path e.g.     fetch(`/api/graph/:id`) and or ${id} however i;ve tried all permutations of url formats and it never hits that function on the backend. 

not sure what else to try - and this is exacerbated by the need to rebuild the webpack every time so takes a while to trouble shoot. 
Help!
the world is ending!

@jasonseminara
@gittheking
@trevorpreston
@mgershowitz
@rapala61

**Comment by indefinitelee** [comment]
ok fetch route is being hit but now something is wrong in mutating the data. 
nothing is being returned to the state. the errors are 
in terminal
```
SyntaxError: Unexpected token < in JSON at position 5
    at Object.parse (native)
    at /Users/admin/code/Indefinitelee Git/FPL-Stats/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
and in console
`App.jsx:74 Uncaught TypeError: Cannot read property 'catch' of undefined(…)`

**Comment by indefinitelee** [comment]
solved- was missing a const id = req.params.id
